config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "games#index"
  resources :games, :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :started_by, class_name: "User", inverse_of: :games, optional: true
  has_many :players

  STATE_INIT = "init"

  def to_s
    code
  end

  def to_param
    code
  end

  def self.find_by_code(code)
    find_by!(code: code.to_s)
  end

  def find_player(actor)
    case actor
    when Visitor
      players.where(visitor_id: actor.id).first
    when User
      players.where(user_id: actor.id).first
    else
      nil
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :user

  def ready?
    false
  end
end

app/models/remember_me_token.rb
class RememberMeToken < ApplicationRecord
  belongs_to :user

  before_create :generate_token!

  def generate_token!
    raise "todo"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :remember_me_tokens
  has_many :players
  has_many :games, inverse_of: :started_by
end

app/models/visitor.rb
class Visitor
  def initialize(id: nil)
    @id ||= SecureRandom.hex(16)
  end

  attr_reader :id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # The User or Visitor who is here.
  # Never returns nil.
  def current_actor
    @current_actor ||= get_current_actor
  end

  private

  def get_current_actor
    get_current_user_from_session ||
      get_current_user_from_remember_me_token ||
      get_or_create_visitor
  end

  def get_current_user_from_session
    User.where(id: session[:current_user_id]).first
  end

  def get_current_user_from_remember_me_token
    token = RememberMeToken.where(token: cookies[:remember_me]).first
    token&.user
  end

  def get_or_create_visitor
    visitor = Visitor.new(id: session[:visitor_id].to_s.presence)
    session[:visitor_id] = visitor.id
    # todo: Also a remember me token?
    visitor
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include CreateGame

  def create
    redirect_to(create_game(actor: current_actor))
  end

  def show
    @game = Game.find_by_code(params[:id])
    @me = @game.find_player(current_actor) || Player.new
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    session[:player_name] = params[:player_name] || "you are a guest"
    redirect_to game_path(id: params[:game_id] || "EXGM12")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_init.html.erb
<h2>Setup</h2>

<h3>Players</h3>
<%= render "players_setup" %>

app/views/games/_join.html.erb
<h1 class="display-4 fw-bold lh-1 mb-3">Join a game</h1>
<%= form_with url: players_path, class: "p-4 p-md-5 border rounded-3 bg-light" do %>
  <div class="form-floating mb-3">
    <input type="text" class="form-control" name="game_id" id="game-id" placeholder="ABCDEF">
    <label for="game-id">Game ID</label>
  </div>
  <div class="form-floating mb-3">
    <input type="text" class="form-control" name="player_name" id="player_name" placeholder="you">
    <label for="player_name">Your Name</label>
  </div>
  <button class="w-100 btn btn-lg btn-primary" type="submit">Join</button>
<% end %>

app/views/games/_other_player_setup.html.erb
<li id="player-setup-<%= player.id %>">
  <b><%= player %></b>
  <% if player.ready? %>ready<% else %>not ready<% end %>
</li>

app/views/games/_player_setup.html.erb
<li id="player-setup-me">
  <input type="text" value="<%= @me.name %>" placeholder="name" data-games-target="my-player-name" data-action="blur->games#set_my_player_name">
  <div class="btn-group" role="group">
    <input type="radio" name="is-ready" value="yes" class="btn-check" id="me-ready" autocomplete="off" <% if @me.ready? %>checked<% end %> data-action="click->games#ready">
    <label class="btn btn-outline-success" for="me-ready">Ready</label>

    <input type="radio" name="is-ready" value="no" class="btn-check" id="me-not-ready" autocomplete="off" <% if !@me.ready? %>checked<% end %> data-action="click->games#not_ready">
    <label class="btn btn-outline-secondary" for="me-not-ready">Not Ready</label>
  </div>
</li>

app/views/games/_players_setup.html.erb
<ol id="games-players-setup">
  <%= render "player_setup" %>
  <% @game.players.each do |player| %>
    <% if @me != player %>
      <%= render "other_player_setup", locals: {player: player} %>
    <% end %>
  <% end %>
</ol>

app/views/games/_start.html.erb
<h1 class="display-4 fw-bold lh-1 mb-3">Start a new game</h1>
<%= form_with url: games_path, class: "p-4 p-md-5 border rounded-3 bg-light" do %>
  <button class="w-100 btn btn-lg btn-primary" type="submit">Start</button>
<% end %>

app/views/games/index.html.erb
<main>
  <div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-6 text-center text-lg-start mx-auto">
        <%= render "start" %>
      </div>
      <hr class="d-block d-lg-none my-3">
      <div class="col-lg-6 text-center text-lg-start mx-auto">
        <%= render "join" %>
      </div>
    </div>
    <div class="row">
      todo: list games i'm already playing.
    </div>
  </div>
</main>

app/views/games/show.html.erb
<h1>Game <%= @game %></h1>
<div data-controller="games">
  <%= render @game.state %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ඞඞඞ Family Chores ඞඞඞ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>